[build]
base = "client"
publish = "dist"
command = "npm run build"

[build.environment]
  VITE_API_URL = "https://campus-problem-intelligence-systems.onrender.com"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
